env: local

llm:
  host: 0.0.0.0
  port: 8001
  models:
    - name: ChatGLM4-6B-Q5_1
      path: /home/zzt/models/llm/chatglm3/6b-q5_1/chatglm3-q5_1.bin

rag:
  host: 0.0.0.0
  port: 8000

vector_store:
  index_path: data/vector_store/faiss.index
  meta_path: data/vector_store/metadata.json
  map_path: data/vector_store/doc_map.json
  embed_path: data/vector_store/article_embeddings.npz

ui:
  host: 0.0.0.0
  rag_port: 8501
  vdb_port: 8502